"Filed out from Dolphin Smalltalk 7"!

UI.Tests.ImageViewAbstractTest subclass: #'UI.Tests.ImageListViewTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
UI.Tests.ImageListViewTest guid: (Core.GUID fromString: '{9e3fdff9-1f55-4b2e-8b02-1c766aa4b56b}')!
UI.Tests.ImageListViewTest comment: ''!
!UI.Tests.ImageListViewTest categoriesForClass!Unclassified! !
!UI.Tests.ImageListViewTest methodsFor!

classToTest
	^ImageListView!

image
	^IconImageManager current imageListWithExtent: 16@16! !
!UI.Tests.ImageListViewTest categoriesFor: #classToTest!helpers!private! !
!UI.Tests.ImageListViewTest categoriesFor: #image!private!Running! !

